/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_care_audio_CareAudioJNI */

#ifndef _Included_com_care_audio_CareAudioJNI
#define _Included_com_care_audio_CareAudioJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_care_audio_CareAudioJNI
 * Method:    processAudio
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_care_audio_CareAudioJNI_processAudio
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
