/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_care_audio_AudioProcessor */

#ifndef _Included_com_care_audio_AudioProcessor
#define _Included_com_care_audio_AudioProcessor
#ifdef __cplusplus
extern "C" {
#endif
#undef com_care_audio_AudioProcessor_CHUNK_SIZE_20MS
#define com_care_audio_AudioProcessor_CHUNK_SIZE_20MS 160L
#undef com_care_audio_AudioProcessor_CHUNK_SIZE_10MS
#define com_care_audio_AudioProcessor_CHUNK_SIZE_10MS 80L
/*
 * Class:     com_care_audio_AudioProcessor
 * Method:    nativeInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_care_audio_AudioProcessor_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_care_audio_AudioProcessor
 * Method:    nativeProcess
 * Signature: (J[S[S)V
 */
JNIEXPORT void JNICALL Java_com_care_audio_AudioProcessor_nativeProcess
  (JNIEnv *, jobject, jlong, jshortArray, jshortArray);

/*
 * Class:     com_care_audio_AudioProcessor
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_care_audio_AudioProcessor_nativeDestroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
